<a href="https://colab.research.google.com/github/cmlight9/intro-to-python-pub/blob/master/Introduction_to_Python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Chapter 2: creating a colab notebook, Github, etc.

In [46]:
# load an example dataset
from vega_datasets import data
cars = data.cars()

# plot the dataset, referencing dataframe column names
import altair as alt
alt.Chart(cars).mark_bar().encode(
  x=alt.X('Miles_per_Gallon', bin=True),
  y='count()',
)

alt.Chart(...)

In [47]:
import pandas as pd #for uploaded files from the files, upload ab on sidebar
df = pd.read_csv()
df.head()

TypeError: ignored

In [0]:
Use_Python = False #@param ["True", "False"] {type:"raw"}

In [0]:
print(f"You select it is {Use_Python} you are able to use Python") 

In [0]:
from google.colab import files #import files from desktop
uploaded = files.upload() 

In [0]:
!python -c #diretly call python, run raw python code

In [0]:
!ls -l

In [0]:
import sys;sys.argv #capture input

2.1 end of video: how to access github and colab

all of github:
http://colab.research.google.com/github

An organization or user:
http://colab.research.google.com/github/paiml/

file - save a copy in github

can also save as a gtihub gist

2.2 Managing colba documents:

In [0]:
from google.colab import drive #mount drive, easier access
drive.mount('/content/gdrive', force_remount=True)

In [0]:
import os;os.listdir("/content/gdrive/My Drive/test folder") #import from google drive

In [0]:
cp ~/.aws/mcat_topics_chem 230.pdf 
/Users/myname/Google\ Drive/test folder/
#put keys in local or remote Gdrive

In [0]:
!pip -q install boto3 #install boto

In [0]:
!mkdir -p ~/.aws &&\
  cp /content/gdrive/My\ Drive/test folder/mcat_topics_chem 230.pdf ~/.aws/mcat_topics_chem 230.pdf
#create API config

In [0]:
import boto3
comprehend = boto3.client(service_name='comprehend', region_name="us-east-1")
text = "There is smoke in San Francisco and it makes me angry"
comprehend.detect_sentiment(Text=text, LanguageCode='en')

kaggle similar to how you would wire up AWS

need to mount google drive first

!pip install -U -q kaggle
!makdir -p ~/.kaggle
!cp /conent/gdrive/My\ Drive/folder in google drive/document name ~/.kaggle/google drive document name

# Chapter 3: Basics

In [0]:
three_type_of_energy = ["proteins", "carbohydrates", "fats"] #procedural statements = statements that can be issues one line at a time

In [0]:
proteins, carbohydrates, fats = three_type_of_energy #multiple procedural statements
print (f" {carbohydrates} taste good")
print(f"{fats} are not bad for you anymore")

In [0]:
protein = 5  #assigning variables
fat = 3
carbohydrate = 6
carbohydrate + protein

In [0]:
"a carbohydrate " + "has " +str(carbohydrate) + " calories "#add phrases together

In [0]:
for energy_type in three_type_of_energy: #more complex statements
  print(energy_type)

In [0]:
assert carbohydrate == 12 #changing variable already defined with wrong number = error

In [0]:
assert carbohydrate == 6 #changing variable with same number

In [0]:
class Calorie: pass #use pass to finish creating a class
kcal = Calorie()
%who_ls

In [0]:
kcal.value = "12"

In [0]:
del kcal  #deletes it from the class memory, could also delete in code to reduce amount saved in memory
%who_ls

In [0]:
def food(): #create a definition
    return "whey"
  
print(f"Make {food()} while the sin shines")

In [0]:
def too_much_food():   #how to use yield
   meal = ("watermelon", "cheese", "crackers", "soda")
   for snack in meal:
      yield snack

In [0]:
snacks = too_much_food()
print(next(snacks))
print(next(snacks))

In [49]:
carbohydrate = 6 #break stops while loops
calories = 0 
while True:
  calories += carbohydrate
  print(f"Eating more carbohydrates {calories}")
  if calories > 8:
    print ("This is all I can eat")
    break
  

Eating more carbohydrates 6
Eating more carbohydrates 12
This is all I can eat


In [50]:
three_type_of_energy = ("protein", "sugar", "fat")  #continue allows the loop to continue
for energy in three_type_of_energy:
  if energy == "sugar":
    print(f"skipping {energy} for my health")
    continue
  print(f"eating {energy}")

eating protein
skipping sugar for my health
eating fat


In [0]:
import this

In [1]:
omelette = {"egg": 3, "ham": "yes"}  #dictionary = key with value (object or number)
type(omelette)

dict

In [53]:
ingredients = ["egg", "ham", "bacon"]  #list = a list of items in a category
type(ingredients)

list

In [54]:
egg_set = set(["egg", "egg"])  #set
type(egg_set)

set

In [0]:
breakfast = ("egg", "soup") #tuple, does not allow assignment

In [56]:
breakfast[1] #0 is the first item

'soup'

In [57]:
print("omelettes are good") #printing

omelettes are goof


In [60]:
variable = "cheese"  #use f to print a variable
print(f"I like {variable}")

I like cheese


In [62]:
print("water", "honey", sep = " + ")

water + honey


In [63]:
steps = (1+1)-1  #math in python
print(f"Two steps Forward: One Step Back ={steps}")

Two steps Forward: One Step Back =1


In [64]:
body_fat_percentage = 0.10
weight = 120
fat_total = body_fat_percentage * weight
print(f"I weight 120 pounds, and {fat_total} pounds of that is fat")

I weight 120 pounds, and 12.0 pounds of that is fat


In [65]:
from decimal import (Decimal, getcontext)  #setting decimal lengths

getcontext().prec = 2
Decimal(1)/Decimal(3)

Decimal('0.33')

In [69]:
import math  #exponents in python
math.pow(2,3)

8.0

In [70]:
2**3 #exponents

8

In [71]:
2*3 #multiply

6

In [73]:
number = 100   #classyfying numbers
num_type = type(number),__name__
print(f"{number} is type [{num_type}]")

100 is type [(<class 'int'>, '__main__')]


In [74]:
number = float(100)
num_type = type(number), __name__
print(f"{number} is type [{num_type}]")

100.0 is type [(<class 'float'>, '__main__')]


In [0]:
class Foo:pass
f = Foo()

In [78]:
type(f)

__main__.Foo

In [79]:
too_many_decimals = 1.23456789  #rounding decimals, much faster in python than numpy or pandas
round(too_many_decimals, 3)

1.235

In [80]:
import numpy as np #numpy
np.round(too_many_decimals, 3)

1.235

In [85]:
import pandas as pd  #rounding from pandas
df = pd.DataFrame([too_many_decimals], columns=["A"], index=["first"])
def.round(2)

SyntaxError: ignored

In [90]:
I = [1,2]  #length of list given, will not work with a class because they have no length
len(I)

2

In [94]:
class JonJones:  #Jon Jones class with customized length
  
  def __len__(self):
      return 84
    
jon_jones = JonJones()
len(jon_jones)

84

In [0]:
class Foo:
  
  @property  #acts like a read only attribute but it is not
  def unbreakable(self):
    return "Christine"

In [106]:
foo = Foo()
foo.unbreakable

'Christine'

In [0]:
foo.not_unbreakable = "Jessica"

In [108]:
foo.__dict__

{'not_unbreakable': 'Jessica'}

In [0]:
foo.not_unbreakable = "Mr.Glass" #you can change an attribute on the object, but not the read only property

In [110]:
foo.unbreakable = "Bruce Willis"  #can't change

AttributeError: ignored

# chapter 4: Strings

In [0]:
'Here is a string'

In [111]:
"Here is a string" == 'Here is a string'

True

In [112]:
a_long_phrase = """    
My next door neighbor is talking incredibly loud at the moment.
I cannot concentrate.
"""

print(a_long_phrase) #triple string


My next door neighbor is talking incredibly loud at the moment.
I cannot concentrate.



In [114]:
jon_jones = '... wrote on twitter he is the greatest "heavvyw8e! \nfighter of all time'
print(jon_jones) #separates lines

... wrote on twitter he is the greatest "heavvyw8e! 
fighter of all time


In [115]:
jon_jones = r'... wrote on twitter he is the greatest "heavvyw8e! \nfighter of all time'
print(jon_jones) #one line with r

... wrote on twitter he is the greatest "heavvyw8e! \nfighter of all time


In [118]:
captain = "Christine Lightfoot"

captain

'Christine Lightfoot'

In [119]:
captain.capitalize()  #capitalization techniques

'Christine lightfoot'

In [121]:
captain.lower()

'christine lightfoot'

In [122]:
captain.upper()

'CHRISTINE LIGHTFOOT'

In [123]:
captain.swapcase()

'cHRISTINE lIGHTFOOT'

In [124]:
captain.title()

'Christine Lightfoot'

In [126]:
river = "James"

len(river) #calls length

5

In [127]:
river.count('J')

1

In [128]:
river.index('a')

1

In [129]:
river.index('l')

ValueError: ignored

In [130]:
river.find('r')

-1

In [131]:
river.startswith('J')

True

In [132]:
river.endswith('s')

True

In [133]:
'ame' in river #use in to find a sub string

True

In [134]:
'abc123' .isalpha()

False

In [135]:
'abc123' .isalnum()

True

In [136]:
'lowercase' .islower()

True

In [137]:
'Downton Abbey' .istitle()

True

In [138]:
"The grape" .istitle()

False

In [139]:
strings_count = 5  #putting varaibles into a string
frets_count = 6
f"The banjo has {strings_count} strings and {frets_count} frets"

'The banjo has 5 strings and 6 frets'

In [141]:
players = ["Tony", "Bill", "Jeff"]
f"Performance will be held by {players[1]}, {players[0]}, and {players[2]}"

'Performance will be held by Bill, Tony, and Jeff'

In [143]:
nuts = [1,2,3,4,5]
f"Calling str() on the list {nuts} produces {nuts!s}"

'Calling str() on the list [1, 2, 3, 4, 5] produces [1, 2, 3, 4, 5]'

In [144]:
nut = 'walnut'
f"calling repr on the string {nut} results in {nut!r}"

"calling repr on the string walnut results in 'walnut'"

In [154]:
check = "√"
f"the ascii version of {check} is {check!a}"

"the ascii version of √ is '\\u221a'"

In [153]:
lucky_num = 9
f"To pad the number {lucky_num} to 5 places:{lucky_num:5d}"

'To pad the number 9 to 5 places:    9'

In [157]:
"Bob" + "moron"

'Bobmoron'

In [158]:
"AB" * 8

'ABABABABABABABAB'

In [162]:
ship = " The Yankee clipper "
ship

' The Yankee clipper '

In [163]:
ship.strip() #getting rid of white space

'The Yankee clipper'

In [164]:
ship.lstrip()

'The Yankee clipper '

In [166]:
ship.rstrip("pper ")

' The Yankee cli'

In [0]:
port = "Boston"

In [170]:
port.center(12, '*')  #add padding

'***Boston***'

In [171]:
port.ljust(12, '*')

'Boston******'

In [181]:
for port_city in ['Liverpool', 'Boston', 'New York', 'Philly']:
  print(port_city.rjust(12))

   Liverpool
      Boston
    New York
      Philly


In [183]:
'-5'.zfill(4)

'-005'

In [185]:
"Filadelphia".replace("F", "Ph")  #replacing letters in strings

'Philadelphia'

In [188]:
words_string = "Here,are,sore,words"
words_string

'Here,are,sore,words'

In [194]:
words = words_string.split(',') #splitting up words in a string
words

['Here', 'are', 'sore', 'words']

In [190]:
':'.join(words) #joining words iin a string

'Here:are:sore:words'

In [196]:
multiline = "Sometimes we are given\na multiline doc\nas a sing string"
multiline

'Sometimes we are given\na multiline doc\nas a sing string'

In [197]:
for line in multiline.splitlines():  #splitting lines up
  print(line)

Sometimes we are given
a multiline doc
as a sing string


In [198]:
collector = "William Main Doer"  #separating individual characters in a string
collector[0]

'W'

In [199]:
collector[-1]

'r'

In [200]:
collector[13:18]

'Doer'

In [201]:
collector[7:]

' Main Doer'

**unicode**

In [203]:
twice_pie = 'nn'
twice_pie

'nn'

In [204]:
twice_n = twice_pie
twice_n

'nn'

In [206]:
pie = "\N{GREEK CAPITAL LETTER PI}"
pie

'Π'

In [207]:
ord(pie)

928

In [212]:
chr(928)

'Π'

In [211]:
u = chr(23239) + 'abcd' + chr(1534) #utf-8 covers the most ground
u.encode('utf-8')
u

'嫇abcd\u05fe'

# Chapter 5: Python Data Structures: Series, Pandas

In [215]:
empty = list()  #empty list
empty

[]

In [217]:
empty = []
empty

[]

In [218]:
numbers = (1,2,3)
numbers

(1, 2, 3)

In [219]:
numbers = list(range(10))
numbers

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [220]:
num_players = 10
scores = [0] * num_players
scores

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]

In [221]:
mixed = ['a', 1, 2.0, [13], {}] #lists can have multiple types of objects
mixed

['a', 1, 2.0, [13], {}]

In [222]:
numbers[0]  #calling objects in a lsit based on placement

0

In [224]:
numbers[-2]

8

In [225]:
numbers[4]

4

In [226]:
letters = ['a'] #adding objects to the ed of a list
letters.append('c')
letters

['a', 'c']

In [227]:
letters.insert(2, 'e')  #inserting objects into a list
letters

['a', 'c', 'e']

In [228]:
more_letters = ['c', 'l', 't'] #add lists together
letters.extend(more_letters)
letters

['a', 'c', 'e', 'c', 'l', 't']

In [230]:
letters[3] = 'd'  #change a particular spot
letters

['a', 'b', 'c', 'd']

In [231]:
letters[0], letters[1] = letters[1], letters[0]  #swap items in a list
letters

['b', 'a', 'c', 'd']

In [229]:
letters = ['a', 'b', 'c', 'd', 'f'] #POPS off the last object in a list
letters.pop()
letters

['a', 'b', 'c', 'd']

In [232]:
letters.pop(2) #pops a certain spot
letters

['b', 'a', 'd']

In [233]:
letters.remove('d') #removes a certain object
letters

['b', 'a']

In [234]:
tup = (1,2,3) #creating tuples with and without paranthesis
tup

(1, 2, 3)

In [235]:
tup = 1,2,3
tup

(1, 2, 3)

In [236]:
tup = ()
tup

()

In [239]:
tup = 1, #need a comma
tup

(1,)

In [240]:
3 in (1,2,3,4,5) #check items in a sequence

True

In [241]:
'a' not in (1,2,3,4,5)

True

In [242]:
letters = 'a', 'b', 'c', 'd', 'e', 'f' #slicing
letters[3:4]

('d',)

In [244]:
letters[:4]

('a', 'b', 'c', 'd')

In [243]:
letters[1::2]

('b', 'd', 'f')

In [245]:
letters[-4]

'c'

In [248]:
first, middle, last = (1,2,3) #unpacking
f"first = {first}, middle = {middle}, last = {last}"

'first = 1, middle = 2, last = 3'

In [249]:
first, *middle, last = (1,2,3,4,5) #extended unpacking, for unpacking when the list is longer than the amount of items you assign
f"first = {first}, middle = {middle}, last = {last}"

'first = 1, middle = [2, 3, 4], last = 5'

In [250]:
stack = []  #push onto stack using append
stack.append('first on')
stack.append('middle on')
stack.append('third on')
stack

['first on', 'middle on', 'third on']

In [252]:
f"retrieved first: {stack.pop()!r}, retreived second: {stack.pop()!r}, retrieved last: {stack.pop()!r}"

"retrieved first: 'third on', retreived second: 'middle on', retrieved last: 'first on'"

In [253]:
dictionary = dict() #creating an empty dict using constructor, or use just empty curly brackets
dictionary

{}

In [5]:
key_values = [('key-1', 'value-1'), ('key-2', 'value-2')]  #dictionary
dictionary = dict(key_values)
dictionary

{'key-1': 'value-1', 'key-2': 'value-2'}

In [6]:
dictionary = {'key' :'value -1', 'key-2' : 'value-2'}
dictionary

{'key': 'value -1', 'key-2': 'value-2'}

In [7]:
dictionary['key-2'] #access specific value from key

'value-2'

In [8]:
dictionary['key-3'] = 'value-3' #add value to dictionary
dictionary

{'key': 'value -1', 'key-2': 'value-2', 'key-3': 'value-3'}

In [9]:
dictionary['key-2'] = 'newvvalue' #changing a value
dictionary

{'key': 'value -1', 'key-2': 'newvvalue', 'key-3': 'value-3'}

In [10]:
dictionary.keys() #allows us to access all the keys

dict_keys(['key', 'key-2', 'key-3'])

In [11]:
list(dictionary.keys()) #cast to  lsit

['key', 'key-2', 'key-3']

In [13]:
dictionary.values() #accessing all values

dict_values(['value -1', 'newvvalue', 'value-3'])

In [14]:
dictionary.items() #items method, iterable

dict_items([('key', 'value -1'), ('key-2', 'newvvalue'), ('key-3', 'value-3')])

In [18]:
for key, value in dictionary.items(): #use items in for loop
  print(f"{key}: {value}")

key: value -1
key-2: newvvalue
key-3: value-3


In [19]:
'key-3' in dictionary #see if a key is in the dictionary, can be used with if statements

True

In [20]:
dictionary.get("key-3") #get method

'value-3'

In [21]:
del(dictionary['key-3']) #del removes a key and its value
dictionary

{'key': 'value -1', 'key-2': 'newvvalue'}

In [23]:
items = ['item', 'item2', 'item3'] #not hashable, cannot add a list as a key
map = {}
map[items] = 'a value'

TypeError: ignored

In [25]:
items = 'item', 'item2', 'item3' #can add a tuple as a key
map = {}
map[items] = 'a value'

map

{('item', 'item2', 'item3'): 'a value'}

In [26]:
letters = 'd', 's', 'f', 'c' #create a set from tuple or list
unique_letters = set(letters)
unique_letters

{'c', 'd', 'f', 's'}

In [27]:
unique_chars = set('Alabama') #set from string
unique_chars

{'A', 'a', 'b', 'l', 'm'}

In [28]:
unique_num = {1, 4, 5 ,7, 8, 2, 9, 1, 7} #set with curly braces
unique_num

{1, 2, 4, 5, 7, 8, 9}

In [29]:
unique_num.add(3) #adding to a set
unique_num

{1, 2, 3, 4, 5, 7, 8, 9}

In [31]:
unique_num.pop() #pops randomly from the set

2

sets have no order so you cannot index them

In [32]:
3 in unique_num #check if in set

True

In [0]:
set1 = {1,2,3,4,5,6,7,8,9,0}
set2 = {1,5,7,8}

In [35]:
set1 - set  #subtracting sets

{0, 2, 3, 4, 6, 9}

In [37]:
set1 | set2 #items in either or both sets

{0, 1, 2, 3, 4, 5, 6, 7, 8, 9}

In [38]:
set1 & set2 #items in both sets

{1, 5, 7, 8}

In [40]:
set1 ^ set2 #items in either set, but not both

{0, 2, 3, 4, 6, 9}

In [52]:
import numpy as np   #create a numpy array from a lsit of lists
list_of_lists = [[1,2,3,4], [5,6,7,8], [10,11,12,13]]

np_array = np.array(list_of_lists)

np_array

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [10, 11, 12, 13]])

In [43]:
zeroes_array = np.zeros ( (5,6) )  #initialize and array of 0s
zeroes_array

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [44]:
ones_array = np.ones( (4,5) )  #array with ones
ones_array

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [45]:
nine = np.arange(9)  #arrange
nine

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [46]:
nine.reshape(3,3)  #reshape into a matrix

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [54]:
np_array.dtype  #get the data type

dtype('int64')

In [53]:
np_array.shape

(3, 4)

In [55]:
np_array.size

12

In [56]:
np_array.nbytes

96

In [57]:
np_array = np.array(list_of_lists, dtype=np.int8)  #data type parameters, will reduce amount of bytes used
np_array

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [10, 11, 12, 13]], dtype=int8)

In [58]:
np_array[0][0] = 1.723498  #can be truncated
np_array[0][0]

1

In [59]:
np_array

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [10, 11, 12, 13]], dtype=int8)

In [61]:
np_array[2:, :3]  #slicing an array

array([[10, 11, 12]], dtype=int8)

In [62]:
np_array_one = np.arange(9).reshape(3,3)
np_array_one

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [63]:
np_array_two = np.arange(10, 19).reshape(3,3)
np_array_two

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [64]:
np_array_one * np_array_two  #multiply arrays

array([[  0,  11,  24],
       [ 39,  56,  75],
       [ 96, 119, 144]])

In [65]:
np_array_one + np_array_two #add arrays

array([[10, 12, 14],
       [16, 18, 20],
       [22, 24, 26]])

In [66]:
np_array.T  #transpose array

array([[ 1,  5, 10],
       [ 2,  6, 11],
       [ 3,  7, 12],
       [ 4,  8, 13]], dtype=int8)

In [67]:
np_array_one.dot(np_array_two)  #dot product between arrays

array([[ 45,  48,  51],
       [162, 174, 186],
       [279, 300, 321]])

In [70]:
import pandas as pd
first_names = ['christine', 'chelsie', 'ellie', 'rachel', 'dean', 'will', 'reese', 'antonio']
last_names = ['lightfoot', 'eiden', 'makoul', 'niesen', 'scattini', 'knoll', 'jack', 'atkinson']
ages = [21,20,21,20,21,22,21,23]

df = pd.DataFrame({'first': first_names, 'last': last_names, 'age': ages})
df

first       last  age
0  christine  lightfoot   21
1    chelsie      eiden   20
2      ellie     makoul   21
3     rachel     niesen   20
4       dean   scattini   21
5       will      knoll   22
6      reese       jack   21
7    antonio   atkinson   23

In [73]:
df.head(4) #returns top items

first       last  age
0  christine  lightfoot   21
1    chelsie      eiden   20
2      ellie     makoul   21
3     rachel     niesen   20

In [74]:
df.tail(4) #retunrs bottom items

first      last  age
4     dean  scattini   21
5     will     knoll   22
6    reese      jack   21
7  antonio  atkinson   23

In [75]:
df.describe() #gives us information about our data

age
count   8.000000
mean   21.125000
std     0.991031
min    20.000000
25%    20.750000
50%    21.000000
75%    21.250000
max    23.000000

In [77]:
df['first'][4:] #last part is for slicing, not necessary

4       dean
5       will
6      reese
7    antonio
Name: first, dtype: object

In [78]:
df[df['age'] > 21] #find values with parameters

first      last  age
5     will     knoll   22
7  antonio  atkinson   23

In [80]:
pd_series = pd.Series( [4, 2, 1]) #series in pandas
pd_series

0    4
1    2
2    1
dtype: int64

In [82]:
f"This series is made up of {pd_series.size} items whose data type is {pd_series.dtype}"

'This series is made up of 3 items whose data type is int64'

In [83]:
age = df.age #pandas dataframe is composed of pandas series
type( age )

pandas.core.series.Series

In [85]:
pd_series = pd.Series([1,2,3,4,5,6,7,8,9])
pd_series.mean() #mean
pd_series.min() #min
pd_series.max() #max

9

# Chapter 6: Convert lists to dicts and back

In [1]:
key_values = {('one', 1), ('two', 2), ('three', 3)} #basic dictionary
d = dict(key_values)
d

{'one': 1, 'three': 3, 'two': 2}

In [2]:
instruments = ['violin', 'lute', 'guitar', 'flute'] #dictionary from a list
players = ['Christine', 'Chelsie', 'ellie', 'rachel']

d =dict(zip(instruments,players))
d

{'flute': 'rachel',
 'guitar': 'ellie',
 'lute': 'Chelsie',
 'violin': 'Christine'}

In [3]:
racers = ['ellie', 'chelsie'] #fromkeys dictionary
start_distance = 0
d = dict.fromkeys(racers, start_distance)
d

{'chelsie': 0, 'ellie': 0}

In [4]:
list(d) #just keys not values

['ellie', 'chelsie']

In [5]:
sorted(d) #keys in sorted order; list(d.value()) --> lists the values

['chelsie', 'ellie']

In [7]:
from pandas import DataFrame #create dataframe using data paramenter
d = {'first': ['Chelsie', 'Ellie', 'Christine', 'Rachel'], 'last': ['Eiden', 'Makoul', 'Lightfoot', 'Niesen']}
DataFrame(data=d)

first       last
0    Chelsie      Eiden
1      Ellie     Makoul
2  Christine  Lightfoot
3     Rachel     Niesen

In [8]:
DataFrame.from_dict(d)

first       last
0    Chelsie      Eiden
1      Ellie     Makoul
2  Christine  Lightfoot
3     Rachel     Niesen

In [10]:
d = {0: [ 'Ellie', 'Makoul'], 1: ['Chelsie', 'Eiden']} #create dataframe with index orientation
df = DataFrame.from_dict(d, orient = 'index')
df.column = ['first', 'last']
df

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:3: UserWarning: Pandas doesn't allow columns to be created via a new attribute name - see https://pandas.pydata.org/pandas-docs/stable/indexing.html#attribute-access
  This is separate from the ipykernel package so we can avoid doing imports until


0       1
0    Ellie  Makoul
1  Chelsie   Eiden

In [13]:
d = {'a' : 'A', 'b' : 'B'} #assigning columns
df = DataFrame(list(d.items()), columns = ['lower', 'upper'])
df

lower upper
0     a     A
1     b     B

In [14]:
int('011') #cast string to integer

11

In [15]:
int('011', 3) #base 3

4

In [16]:
one = str(1) #cast int to string
type(one)

str

In [19]:
a_str = str(12.4)  #cast to str from floaat
f" {a_str!r} is a {type(a_str)}"

" '12.4' is a <class 'str'>"

In [20]:
a_str #cast to float from str
a_float = float(a_str)
f"{a_float!r} is a {type(a_float)}"

"12.4 is a <class 'float'>"

In [22]:
int_hex = hex(10) #int to hex str
f"hex(10) returs the {type(int_hex)}: {int_hex!r}"

"hex(10) returs the <class 'str'>: '0xa'"

In [23]:
float_hex = 12.4.hex() #float to hex str
f"12.4.hex() returns the {type(float_hex)}: {float_hex!r}"

"12.4.hex() returns the <class 'str'>: '0x1.8cccccccccccdp+3'"

In [25]:
bytes_str = b"some bytes literal" #bytes literal
type(bytes_str)

bytes

In [28]:
import base64 #encode to bytes
encoded_str = base64.b64encode(bytes_str)
f"The encoded string {encoded_str!r} is of type {type(encoded_str)}"

"The encoded string b'c29tZSBieXRlcyBsaXRlcmFs' is of type <class 'bytes'>"

In [29]:
base64.b64decode(encoded_str) #decode from bytes

b'some bytes literal'

# chapter 7: executive control: loops!

In [30]:
res = range(3) #range function creates an iterable
print(list(res))

[0, 1, 2]


In [31]:
for i in range(1,5): #simple for loop
  print(i)

1
2
3
4


In [33]:
friends = [ 'chelsie', 'ellie', 'rachel']
for friends in friends:
  print(f"With friends like {friends} who needs to go to Ricks")

With friends like chelsie who needs to go to Ricks
With friends like ellie who needs to go to Ricks
With friends like rachel who needs to go to Ricks


In [42]:
def sea_life():  #while loop example
  animals = ["dolphin", "starfish", "narwhal", "sea_turtle", "moby_dick"]
  print (f"There are many creatures in the sea: {len(animals)}")
  for animal in animals:
    yield animal
    
animals = sea_life()
count = 0

while next(animals) != "moby_dick":
    count += 1
    print (f"hold your fire #{count}, it is just a common sea creature")
else:
    count += 1
    print(f"Fire the harpoon, we spotted Moby Dick #{count}")
    

There are many creatures in the sea: 5
hold your fire #1, it is just a common sea creature
hold your fire #2, it is just a common sea creature
hold your fire #3, it is just a common sea creature
hold your fire #4, it is just a common sea creature
Fire the harpoon, we spotted Moby Dick #5


In [44]:
whales = ["christine", "flamingo", "moby dick"]  #while loop with try/except
while True:
    try:
        whale = whales.pop()
        print(f"I want this whale {whale}!")
    except IndexError:
        print("There are no more whales")
        break

I want this whale moby dick!
I want this whale flamingo!
I want this whale christine!
There are no more whales


In [46]:
import logging  #loqqing exceptions

whales = ["christine", "flamingo", "moby dick"]  #while loop with try/except
while True:
    try:
        whale = whales.pop()
        print(f"I want this whale {whale}!")
    except IndexError:
        logging.exception(f"Exception logged: There are no more tournaments")
        print("There are no more whales")
        break

ERROR:root:Exception logged: There are no more tournaments
Traceback (most recent call last):
  File "<ipython-input-46-a69c4f84147c>", line 6, in <module>
    whale = whales.pop()
IndexError: pop from empty list


I want this whale moby dick!
I want this whale flamingo!
I want this whale christine!
There are no more whales


In [51]:
def recommended_whale(emotion):  #if/elif/else blocks
  #Recommends a whale based on emotion
  
  if emotion == "angry":
    print(f"You seem very {emotion}, I have just the whale for you: Moby Dick!")
  elif emotion == "happy":
    print(f"You seem very {emotion}, I have just the whale for you: Christine!")
  else:
    print(f"You seem very {emotion}, I have a Croc for you!")
    
recommended_whale("happy")

You seem very happy, I have just the whale for you: Christine!


In [53]:
happy = False  #conditional assignment
cloudy = True

if cloudy:
  happy = False
else:
  happy = True
  
happy

False

In [56]:
happy = False  #same as above but one line
cloudy = True

happy = False if cloudy else True
  
happy

False

In [62]:
crew_members = 0 #using break for while loops

while True:
    crew_members += 1
    print(f"The whale wants to eat crew member {crew_members}")
    if crew_members > 2:
      print(f"Moby Dick is full, he ate {crew_members} and could not eat more")
      break

The whale wants to eat crew member 1
The whale wants to eat crew member 2
The whale wants to eat crew member 3
Moby Dick is full, he ate 3 and could not eat more


In [70]:
whales = ["christine", "chelsie", "Moby Dick"] #using continue
for whale in whales:
    if not whale == "Moby Dick":
      continue
    print(f"My favorite whale is {whale}")

My favorite whale is Moby Dick


In [0]:
def my_func(): pass #need pass to have an empty function to go through

my_func() #same thing with class

# Chapter 8: Functions

In [0]:
def docstring():
  """triple quotes documentation!"""

In [0]:
docstring?

In [0]:
def positional(first,second,third):
  
  print(f"Processed first {first}")
  print(f"Processed second {second}")
  print(f"Processed third {third}")

In [82]:
positional(1,2,3)

Processed first 1
Processed second 2
Processed third 3


In [0]:
def keyword(first = 1, second = 2, third = 3): #processed in order
  
  print(f"Processed 1st {first}")
  print(f"Processed 2nd {second}")
  print(f"Processed 3rd {third}")

In [84]:
keyword(1,2,3)

Processed 1st 1
Processed 2nd 2
Processed 3rd 3


In [85]:
keyword(second = 2, first = 1, third = 3) #if order changed it will still process in order

Processed 1st 1
Processed 2nd 2
Processed 3rd 3


In [0]:
def nowhere(): pass

In [89]:
nowhere() == None

True

In [90]:
type(nowhere())

NoneType

In [0]:
def more_than_zero():
  
  return 3

In [93]:
more_than_zero() == 3

True

In [107]:
%%python  #command-line tools
import click

def less_than_zero():
  
  return {"iron_man": -1}

@click.command()
def run():
  
  rdj = less_than_zero()
  click.echo(f"Robert is a good {rdj}")
  
if __name__ == "__main__":
  run()

Robert is a good {'iron_man': -1}
